server:
  port: 2645

spring:
  application:
    name: KAFKA-SERVICE
  profiles:
    active: @spring.profiles.active@
  main:
    allow-circular-references: true

management:
  metrics:
    export:
      prometheus:
        step: 5s
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
